#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 EvoMap

'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const PLUGIN_FILE_NAME = 'evolver.js';
const PLUGIN_HEADER = '// _evolver_managed: true (do not remove this line)';
const EVOLVER_MARKER = '<!-- evolver-opencode-evolution-memory -->';
const HOOK_SCRIPTS = ['session-start.js', 'signal-detect.js', 'session-end.js'];

function usage() {
  return `Usage: evomap-opencode-plugin [--install|--verify|--uninstall] [--config-root <dir>] [--force]

Installs the local-file OpenCode plugin into <config-root>/.opencode/plugins.
For npm-based OpenCode installs, add "evomap-opencode-plugin" to opencode.json
instead; no CLI install step is required.
`;
}

function parseArgs(argv) {
  const args = {
    action: 'install',
    configRoot: process.cwd(),
    force: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--install') args.action = 'install';
    else if (arg === '--verify') args.action = 'verify';
    else if (arg === '--uninstall') args.action = 'uninstall';
    else if (arg === '--force') args.force = true;
    else if (arg === '--help' || arg === '-h') args.action = 'help';
    else if (arg === '--config-root') {
      i += 1;
      args.configRoot = argv[i] || args.configRoot;
    } else if (arg.startsWith('--config-root=')) {
      args.configRoot = arg.slice('--config-root='.length);
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }
  args.configRoot = path.resolve(args.configRoot);
  return args;
}

function packageRoot() {
  return path.resolve(__dirname, '..');
}

function pluginSource() {
  const serverPath = path.join(packageRoot(), 'server.js');
  return `${PLUGIN_HEADER}
// Auto-generated by evomap-opencode-plugin.
// This file delegates to the package server plugin entrypoint.

module.exports = require(${JSON.stringify(serverPath)});
`;
}

function paths(configRoot) {
  const opencodeDir = path.join(configRoot, '.opencode');
  const pluginsDir = path.join(opencodeDir, 'plugins');
  const pluginPath = path.join(pluginsDir, PLUGIN_FILE_NAME);
  const agentsMdPath = path.join(configRoot, 'AGENTS.md');
  return { opencodeDir, pluginsDir, pluginPath, agentsMdPath };
}

function isManaged(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8').includes('_evolver_managed: true');
  } catch (_err) {
    return false;
  }
}

function appendAgentsSection(filePath) {
  const section = `${EVOLVER_MARKER}
## Evolution Memory (Evolver)

This project uses Evolver for self-evolution. OpenCode plugin hooks automatically:
1. Inject recent evolution memory at session start
2. Detect evolution signals during file edits
3. Record outcomes when the session becomes idle

For substantive tasks, use successful prior approaches when the plugin surfaces them, and avoid repeating failed patterns.`;

  let existing = '';
  try {
    existing = fs.readFileSync(filePath, 'utf8');
  } catch (_err) {
    // new file
  }
  if (existing.includes(EVOLVER_MARKER)) return false;
  const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : '\n';
  fs.writeFileSync(filePath, existing + separator + section + '\n', 'utf8');
  return true;
}

function removeAgentsSection(filePath) {
  try {
    let content = fs.readFileSync(filePath, 'utf8');
    if (!content.includes(EVOLVER_MARKER)) return false;
    const idx = content.indexOf(EVOLVER_MARKER);
    const nextSection = content.indexOf('\n## ', idx + EVOLVER_MARKER.length);
    const endIdx = nextSection === -1 ? content.length : nextSection;
    content = content.slice(0, idx).trimEnd() + (nextSection === -1 ? '' : content.slice(endIdx));
    fs.writeFileSync(filePath, content.trimEnd() + '\n', 'utf8');
    return true;
  } catch (_err) {
    return false;
  }
}

function install({ configRoot, force }) {
  const p = paths(configRoot);
  if (fs.existsSync(p.pluginPath) && !isManaged(p.pluginPath) && !force) {
    return {
      ok: false,
      error: `refusing to overwrite user-owned plugin: ${p.pluginPath}`,
    };
  }
  fs.mkdirSync(p.pluginsDir, { recursive: true });
  const tmp = p.pluginPath + '.tmp';
  fs.writeFileSync(tmp, pluginSource(), 'utf8');
  fs.renameSync(tmp, p.pluginPath);
  appendAgentsSection(p.agentsMdPath);
  return {
    ok: true,
    action: 'install',
    plugin_path: p.pluginPath,
    config_root: configRoot,
  };
}

function verify({ configRoot }) {
  const p = paths(configRoot);
  const checks = [];
  const pluginExists = fs.existsSync(p.pluginPath);
  checks.push({
    id: 'plugin_file_present',
    ok: pluginExists,
    detail: pluginExists ? p.pluginPath : `missing: ${p.pluginPath}`,
  });
  const managed = pluginExists && isManaged(p.pluginPath);
  checks.push({
    id: 'plugin_managed_marker',
    ok: managed,
    detail: managed ? 'contains _evolver_managed: true' : 'plugin file is absent or user-owned',
  });

  let loadable = false;
  let loadError = null;
  if (pluginExists) {
    try {
      delete require.cache[require.resolve(p.pluginPath)];
      const mod = require(p.pluginPath);
      loadable = typeof (mod && (mod.Evolver || mod.default)) === 'function';
      if (!loadable) loadError = 'missing Evolver/default function export';
    } catch (err) {
      loadError = (err && err.message) || String(err);
    }
  }
  checks.push({
    id: 'plugin_loadable',
    ok: loadable,
    detail: loadable ? 'require() succeeded and exports Evolver()' : `require() failed: ${loadError || 'unknown'}`,
  });

  const missingHooks = HOOK_SCRIPTS.filter((name) => !fs.existsSync(path.join(packageRoot(), 'hooks', name)));
  checks.push({
    id: 'package_hooks_present',
    ok: missingHooks.length === 0,
    detail: missingHooks.length === 0
      ? 'all package hook scripts present'
      : `missing from package: ${missingHooks.join(', ')}`,
  });

  let hasAgents = false;
  try {
    hasAgents = fs.readFileSync(p.agentsMdPath, 'utf8').includes(EVOLVER_MARKER);
  } catch (_err) {
    hasAgents = false;
  }
  checks.push({
    id: 'agents_md_section',
    ok: hasAgents,
    detail: hasAgents ? 'AGENTS.md contains Evolver OpenCode section' : 'AGENTS.md section not installed',
  });

  return {
    ok: checks.every((check) => check.ok),
    action: 'verify',
    plugin_path: p.pluginPath,
    config_root: configRoot,
    checks,
  };
}

function uninstall({ configRoot }) {
  const p = paths(configRoot);
  let changed = false;
  if (isManaged(p.pluginPath)) {
    fs.unlinkSync(p.pluginPath);
    changed = true;
  }
  if (removeAgentsSection(p.agentsMdPath)) changed = true;
  return {
    ok: true,
    action: 'uninstall',
    removed: changed,
    plugin_path: p.pluginPath,
    config_root: configRoot,
  };
}

function printReport(report) {
  if (report.action === 'verify') {
    console.log(`[opencode] Verify ${report.ok ? 'passed' : 'failed'}`);
    console.log(`[opencode]   plugin path : ${report.plugin_path}`);
    console.log(`[opencode]   config root : ${report.config_root}`);
    for (const check of report.checks) {
      console.log(`[opencode]   ${check.ok ? '[OK]  ' : '[FAIL]'} ${check.id} -- ${check.detail}`);
    }
    return;
  }
  if (report.ok) {
    const verb = report.action === 'uninstall' ? 'Uninstalled' : 'Installed';
    console.log(`[opencode] ${verb} Evolver plugin at ${report.plugin_path}`);
    if (report.action === 'install') {
      console.log('[opencode] Restart OpenCode for the plugin to take effect.');
      console.log('[opencode] For npm installs, prefer adding "evomap-opencode-plugin" to opencode.json.');
    }
  } else {
    console.error(`[opencode] ${report.error || 'operation failed'}`);
  }
}

function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (err) {
    console.error((err && err.message) || String(err));
    console.error(usage());
    process.exit(2);
  }
  if (args.action === 'help') {
    process.stdout.write(usage());
    return;
  }

  let report;
  if (args.action === 'verify') report = verify(args);
  else if (args.action === 'uninstall') report = uninstall(args);
  else report = install(args);

  printReport(report);
  if (!report.ok) process.exit(1);
}

if (require.main === module) {
  main();
}

module.exports = {
  parseArgs,
  pluginSource,
  isManaged,
  install,
  verify,
  uninstall,
  paths,
  packageRoot,
  EVOLVER_MARKER,
};
